### ISSUE TITLE
Fix typos in instructions.

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#161]
* Exercise 1 `App.java` vs. `Api.java` (adding the ESDK dependency)
* Exercise 1 Node.JS has some path errors and `.js` in TypeScript instructions

**Comment by greenpau** [comment]
@lizroth , please see the error below:

```
TeamRole:~/environment/workshop/exercises/python/multi-cmk-complete (master) $ tox -e repl
GLOB sdist-make: /home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/setup.py
repl inst-nodeps: /home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/.tmp/package/1/Busy Engineer's Document Bucket-0.1.0.zip
repl installed: attrs==19.3.0,aws-encryption-sdk==1.4.1,boto3==1.10.29,botocore==1.13.29,Busy-Engineer-s-Document-Bucket==0.1.0,cffi==1.13.2,cryptography==2.8,docutils==0.15.2,jmespath==0.9.4,pycparser==2.19,python-dateutil==2.8.0,s3transfer==0.2.1,six==1.13.0,toml==0.10.0,urllib3==1.25.7,wrapt==1.11.2
repl run-test-pre: PYTHONHASHSEED='3749046151'
repl run-test: commands[0] | python
Python 3.8.0 (default, Dec  2 2019, 22:23:13) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import document_bucket
>>> ops = document_bucket.initialize()
>>> ops.list()
{PointerItem(partition_key='1d0f02a2-2d3d-4823-a129-20fe3838d582', sort_key='S3Object', context={}), PointerItem(partition_key='6214ec99-dbdf-4ac6-a3dc-78ecea524d6c', sort_key='S3Object', context={})}
>>> ops.store(b'some data')
PointerItem(partition_key='b71ad1fd-575d-4e63-a278-96b2b914a058', sort_key='S3Object', context={})
>>> for item in ops.list():
...     print(ops.retrieve(item.partition_key))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/document_bucket/api.py", line 99, in retrieve
    item = self._get_pointer_item(PointerQuery.from_key(pointer_key))
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/document_bucket/api.py", line 51, in _get_pointer_item
    pointer_items = self.table.query(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/client.py", line 633, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/client.py", line 679, in _convert_to_request_dict
    api_params = self._emit_api_params(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/client.py", line 708, in _emit_api_params
    self.meta.events.emit(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 195, in inject_attribute_value_input
    self._transformer.transform(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 253, in transform
    self._transform_parameters(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 260, in _transform_parameters
    getattr(self, '_transform_%s' % type_name)(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 274, in _transform_structure
    self._transform_parameters(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 260, in _transform_parameters
    getattr(self, '_transform_%s' % type_name)(
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/transform.py", line 285, in _transform_map
    params[key] = transformation(value)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/types.py", line 102, in serialize
    dynamodb_type = self._get_dynamodb_type(value)
  File "/home/ec2-user/environment/workshop/exercises/python/multi-cmk-complete/.tox/repl/lib/python3.8/site-packages/boto3/dynamodb/types.py", line 141, in _get_dynamodb_type
    raise TypeError(msg)
TypeError: Unsupported type "<class 'document_bucket.model.UUIDKey'>" for value "b71ad1fd-575d-4e63-a278-96b2b914a058"
>>> 
```

**Comment by greenpau** [comment]
@lizroth , the issue is somewhere here. See the commented out lines:

```
    key: Union[UUID, str]

    def __post_init__(self):
        if isinstance(self.key, str):
            # Validate that the UUID is well formed before continuing.
            self.key = str(UUID(self.key))

    #def __str__(self):
    #    return str(self.key)
```

**Comment by lizroth** [comment]
I send a bogus query to DynamoDB in the `PointerQuery`. I'll push a fix momentarily. Thank you for the catch!
